In [8]:
given_list = [2,7,4,1,3,6]
required_sum = 10
count = 0
def checkSum(given_list,required_sum):
  count = 0
  for i in range(len(given_list)):
    for j in range(len(given_list)):
      if given_list[i] + given_list[j] == required_sum:
          count += 1

  return count//2 # since we need pairs
print(checkSum(given_list,required_sum))

2


In [11]:
given_list = [5,3,8,1,0,4]
def RangeFinder(given_list):
  try:
    if len(given_list) < 3:
      raise Exception("Empty List")
  except Exception as e:
    return "Range determination not possible"
  else:
    min_range = min(given_list)
    max_range = max(given_list)
    return max_range - min_range
print(RangeFinder(given_list))

8


In [38]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
m = 3
def MatrixMultiplier(A,m):
  result = np.linalg.matrix_power(A,m)
  return result
print(MatrixMultiplier(A,m))

[[ 468  576  684]
 [1062 1305 1548]
 [1656 2034 2412]]


In [14]:
def StringFrequencyCount(s):
  frequency = {}
  for i in s:
    if i in frequency:
      frequency[i] += 1
    else:
      frequency[i] = 1
  max_occured = max(frequency.values())
  char = ""
  for i in frequency.keys():
    if frequency[i] == max_occured:
      char = i
  return f"character {char} occured {max_occured} times"
print(StringFrequencyCount("hippopotamus"))

character p occured 3 times


In [34]:
import numpy as np
random_list = list(np.random.randint(0,10,25))
def MeanMedianMode(random_list):
  mean = np.mean(random_list)
  median = np.median(random_list)
  unique, counts = np.unique(random_list, return_counts=True)
  return int(mean),int(median),random_list.index(max(counts))
print(MeanMedianMode(random_list))

(4, 5, 1)
